name: Metrics & Snake
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 生成看板 (去掉了报错的插件，改成了更简洁的样式)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: Elaine-one
          template: classic
          base: header, repositories, metadata
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_activity: no # 关闭这个报错的插件

      # 2. 生成贪吃蛇
      - uses: Platane/snk@v3
        with:
          github_user_name: Elaine-one
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # 3. 将贪吃蛇图片存入仓库
      - name: Push Snake to Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          publish_branch: main # 存放在主分支
          keep_files: true # 重点：不要删除看板图
