name: Snake Game
on:
  schedule: [{cron: "0 0 * * *"}] # 每天凌晨更新
  workflow_dispatch: # 允许手动点击运行
  push: {branches: ["main"]} # 每次向 main 分支推送时更新

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 生成贪吃蛇图片
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Elaine-one
          outputs: |
            github-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # 2. 把生成的图片推送到 output 分支
      - name: Push to Output Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: . 
          publish_branch: output
          publish_assets: "github-snake.svg" # 只搬运蛇，保持分支干净
